spring:
  application:
    name: spring-k8s-cache-webhook-coordinator

management:
  otlp:
    tracing:
      endpoint: http://otel-collector.observability.svc.cluster.local:4318/v1/traces

logging:
  level:
    io.micrometer.tracing: DEBUG
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG
