apiVersion: v1
kind: Service
metadata:
  name: spring-k8s-cache-webhook-coordinator
spec:
  selector:
    app: spring-k8s-cache-webhook-coordinator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Specify the external port for NodePort
  type: NodePort
